# Generated by Django 5.1.7 on 2025-04-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_ratesconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
