# Generated by Django 5.1.7 on 2025-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0006_depositrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingocard',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
