# Generated by Django 5.1.7 on 2025-04-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0007_add_metadata_to_bingocard'),
        ('bingo', 'auto_add_disabled_patterns'),
    ]

    operations = [
    ]
