# Generated by Django 5.1.7 on 2025-04-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0008_merge_20250403_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcoinbalance',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
