# Generated by Django 5.1.7 on 2025-04-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0009_alter_testcoinbalance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='seller_card_price',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=10, verbose_name='Seller Card Price'),
        ),
    ]
