# Generated by Django 5.1.7 on 2025-04-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0010_systemconfig_seller_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcoinbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
