# Generated by Django 5.1.7 on 2025-04-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0011_alter_testcoinbalance_balance_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingocard',
            name='correlative_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bingocard',
            unique_together={('event', 'correlative_id')},
        ),
    ]
