databases:
  - name: bingo_db
    databaseName: bingo
    user: bingo
    plan: free

services:
  - type: web
    name: bingo-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bingo_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: WEB_CONCURRENCY
        value: 4